name: Build PS2 ELF
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev
    steps:
      - uses: actions/checkout@v4
      - run: make
      - uses: actions/upload-artifact@v4
        with:
          name: triangle-elf
          path: triangle.elf
